name: social_media
description: (Poke) Mariam's Socialmedia project for bdaya devlopment training
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  async: ^2.11.0
  bdaya_flutter_common: ^8.0.0
  bdaya_shared_value: ^3.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.1.0
  grpc: ^3.2.4
  http: ^1.2.0
  injectable: ^2.3.2
  intl: ^0.18.0 #Localization
  oidc: ^0.5.1
  oidc_default_store: ^0.2.0+7
  protobuf: ^3.1.0

  #Forms
  reactive_forms: ^16.1.1
  reactive_forms_annotations: ^4.3.0
  # rxdart: ^0.27.7    ####
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.0.1
  url_launcher: ^6.1.70
  url_strategy: ^0.2.0
  uuid: ^4.3.3
  # mason: ^0.1.0-dev.52  ####

  #UI
  # cupertino_icons: ^1.0.2
  # flutter_adaptive_scaffold: ^0.1.0
  # scroll_snap_list: ^0.9.1
  # dio: ^5.4.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  integration_test:
    sdk: flutter
  mason_cli: ^0.1.0-dev.53
  mocktail: ^1.0.0
  reactive_forms_generator: ^4.5.2
  # remane: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/ 
    - assets/colors/ ###
  generate: true
## Linux setUp
# parts:
#   uet-lms:
#     source: .
#     plugin: flutter
#     flutter-target: lib/main.dart
#     build-packages:
#       - libsecret-1-dev
#       - libjsoncpp-dev
#     stage-packages:
#       - libsecret-1-0
#       - libjsoncpp-dev
