name: social_media
description: Mariam's Socialmedia project for bdaya devlopment training
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  async: ^2.11.0
  bdaya_flutter_common: ^8.0.0
  bdaya_shared_value: ^3.1.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.1.0
  grpc: ^3.2.4
  injectable: ^2.3.4
  intl: ^0.18.0
  protobuf: ^3.1.0
  url_strategy: ^0.2.0
  # mason: ^0.1.0-dev.52  ####

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  # remane: ^3.0.1
  mason_cli: ^0.1.0-dev.53
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true
